
import { PERSON_DATA } from './person';
import { GROUP_DATA } from './groups';

export interface EmployeeInterface {
  id: number;
  username: string,
  firstName:string,
  lastName:string,
  email:string,
  birthDate:Date,
  basicSalary:number,
  status:string,
  group:string,
  description:Date
}

export const EMPLOYEE_DATA: EmployeeInterface[] = [
    {
        "id": 1,
        "username": "grace4779",
        "firstName": "Grace",
        "lastName": "Williams",
        "email": "grace4779@company.com",
        "birthDate": new Date("1960-10-25"),
        "basicSalary": 56108.00893889843,
        "status": "Inactive",
        "group": "developer",
        "description": new Date("2001-04-06")
    },
    {
        "id": 2,
        "username": "nancymiller",
        "firstName": "Nancy",
        "lastName": "Miller",
        "email": "nancymiller@mail.com",
        "birthDate": new Date("1977-01-24"),
        "basicSalary": 56922.14543077449,
        "status": "Active",
        "group": "manager",
        "description": new Date("1917-12-20")
    },
    {
        "id": 3,
        "username": "bob.a",
        "firstName": "Bob",
        "lastName": "Robinson",
        "email": "bob.a@mail.com",
        "birthDate": new Date("1969-09-21"),
        "basicSalary": 50953.480542983845,
        "status": "Inactive",
        "group": "finance",
        "description": new Date("1916-01-31")
    },
    {
        "id": 4,
        "username": "oliverwilson",
        "firstName": "Oliver",
        "lastName": "Wilson",
        "email": "oliverwilson@mail.com",
        "birthDate": new Date("1976-01-01"),
        "basicSalary": 70433.66070151748,
        "status": "Active",
        "group": "sales",
        "description": new Date("1983-11-12")
    },
    {
        "id": 5,
        "username": "irene.smith",
        "firstName": "Irene",
        "lastName": "Smith",
        "email": "irene.smith@company.com",
        "birthDate": new Date("1991-07-05"),
        "basicSalary": 68695.90418258915,
        "status": "Inactive",
        "group": "sales",
        "description": new Date("1904-01-04")
    },
    {
        "id": 6,
        "username": "jack_jackson",
        "firstName": "Jack",
        "lastName": "Jackson",
        "email": "jack_jackson@example.com",
        "birthDate": new Date("1967-02-09"),
        "basicSalary": 68920.17295657066,
        "status": "Active",
        "group": "sales",
        "description": new Date("1911-02-08")
    },
    {
        "id": 7,
        "username": "patricia.e",
        "firstName": "Patricia",
        "lastName": "Miller",
        "email": "patricia.e@mail.com",
        "birthDate": new Date("1995-08-17"),
        "basicSalary": 69278.81930207108,
        "status": "Inactive",
        "group": "finance",
        "description": new Date("1943-11-04")
    },
    {
        "id": 8,
        "username": "michael_thompson",
        "firstName": "Michael",
        "lastName": "Thompson",
        "email": "michael_thompson@company.com",
        "birthDate": new Date("1988-05-12"),
        "basicSalary": 72103.89501145044,
        "status": "Active",
        "group": "admin",
        "description": new Date("1979-10-04")
    },
    {
        "id": 9,
        "username": "irene.n",
        "firstName": "Irene",
        "lastName": "Anderson",
        "email": "irene.n@mail.com",
        "birthDate": new Date("1990-12-03"),
        "basicSalary": 65092.5846408836,
        "status": "Inactive",
        "group": "support",
        "description": new Date("1943-04-12")
    },
    {
        "id": 10,
        "username": "michael7758",
        "firstName": "Michael",
        "lastName": "Williams",
        "email": "michael7758@example.com",
        "birthDate": new Date("1997-12-05"),
        "basicSalary": 79986.74864786287,
        "status": "Active",
        "group": "marketing",
        "description": new Date("1966-09-24")
    },
    {
        "id": 11,
        "username": "emily.moore",
        "firstName": "Emily",
        "lastName": "Moore",
        "email": "emily.moore@example.com",
        "birthDate": new Date("1968-12-23"),
        "basicSalary": 59665.7642053666,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1947-11-24")
    },
    {
        "id": 12,
        "username": "patricia.white",
        "firstName": "Patricia",
        "lastName": "White",
        "email": "patricia.white@example.com",
        "birthDate": new Date("1989-09-03"),
        "basicSalary": 58499.73166357559,
        "status": "Active",
        "group": "sales",
        "description": new Date("1996-10-19")
    },
    {
        "id": 13,
        "username": "irene.moore",
        "firstName": "Irene",
        "lastName": "Moore",
        "email": "irene.moore@company.com",
        "birthDate": new Date("1968-09-06"),
        "basicSalary": 50404.04254307899,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1932-02-24")
    },
    {
        "id": 14,
        "username": "emily_smith",
        "firstName": "Emily",
        "lastName": "Smith",
        "email": "emily_smith@test.com",
        "birthDate": new Date("1982-11-23"),
        "basicSalary": 54463.7794229001,
        "status": "Active",
        "group": "admin",
        "description": new Date("1929-08-24")
    },
    {
        "id": 15,
        "username": "david_w",
        "firstName": "David",
        "lastName": "Jones",
        "email": "david_w@company.com",
        "birthDate": new Date("1985-12-18"),
        "basicSalary": 54737.261014557844,
        "status": "Inactive",
        "group": "support",
        "description": new Date("1968-10-22")
    },
    {
        "id": 16,
        "username": "alice_taylor",
        "firstName": "Alice",
        "lastName": "Taylor",
        "email": "alice_taylor@mail.com",
        "birthDate": new Date("2001-11-28"),
        "basicSalary": 71796.06354848467,
        "status": "Active",
        "group": "sales",
        "description": new Date("1924-06-01")
    },
    {
        "id": 17,
        "username": "michael5328",
        "firstName": "Michael",
        "lastName": "Garcia",
        "email": "michael5328@company.com",
        "birthDate": new Date("1995-11-27"),
        "basicSalary": 50068.950585365936,
        "status": "Inactive",
        "group": "hr",
        "description": new Date("1961-09-18")
    },
    {
        "id": 18,
        "username": "kate_wilson",
        "firstName": "Kate",
        "lastName": "Wilson",
        "email": "kate_wilson@test.com",
        "birthDate": new Date("1995-07-08"),
        "basicSalary": 77932.84920936705,
        "status": "Active",
        "group": "finance",
        "description": new Date("1938-06-30")
    },
    {
        "id": 19,
        "username": "emily4647",
        "firstName": "Emily",
        "lastName": "Davis",
        "email": "emily4647@test.com",
        "birthDate": new Date("1994-11-18"),
        "basicSalary": 72301.2706970398,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1987-07-27")
    },
    {
        "id": 20,
        "username": "david0264",
        "firstName": "David",
        "lastName": "White",
        "email": "david0264@example.com",
        "birthDate": new Date("1988-11-22"),
        "basicSalary": 52644.2076781841,
        "status": "Active",
        "group": "qa",
        "description": new Date("1982-10-27")
    },
    {
        "id": 21,
        "username": "grace0444",
        "firstName": "Grace",
        "lastName": "Brown",
        "email": "grace0444@mail.com",
        "birthDate": new Date("2002-07-19"),
        "basicSalary": 61248.92455625841,
        "status": "Inactive",
        "group": "admin",
        "description": new Date("1902-01-11")
    },
    {
        "id": 22,
        "username": "tom3677",
        "firstName": "Tom",
        "lastName": "Johnson",
        "email": "tom3677@example.com",
        "birthDate": new Date("2002-01-22"),
        "basicSalary": 58208.29178914762,
        "status": "Active",
        "group": "operations",
        "description": new Date("1938-03-01")
    },
    {
        "id": 23,
        "username": "grace.anderson",
        "firstName": "Grace",
        "lastName": "Anderson",
        "email": "grace.anderson@mail.com",
        "birthDate": new Date("1997-10-12"),
        "basicSalary": 66502.78575803354,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1953-12-26")
    },
    {
        "id": 24,
        "username": "tom_z",
        "firstName": "Tom",
        "lastName": "Jackson",
        "email": "tom_z@mail.com",
        "birthDate": new Date("1980-12-07"),
        "basicSalary": 73807.10274667531,
        "status": "Active",
        "group": "support",
        "description": new Date("1949-12-04")
    },
    {
        "id": 25,
        "username": "nancy5237",
        "firstName": "Nancy",
        "lastName": "Thomas",
        "email": "nancy5237@company.com",
        "birthDate": new Date("1964-11-22"),
        "basicSalary": 67191.48589744321,
        "status": "Inactive",
        "group": "sales",
        "description": new Date("1942-04-20")
    },
    {
        "id": 26,
        "username": "irene2492",
        "firstName": "Irene",
        "lastName": "Brown",
        "email": "irene2492@company.com",
        "birthDate": new Date("2001-04-05"),
        "basicSalary": 71537.8775247897,
        "status": "Active",
        "group": "hr",
        "description": new Date("1918-04-03")
    },
    {
        "id": 27,
        "username": "gracewilson",
        "firstName": "Grace",
        "lastName": "Wilson",
        "email": "gracewilson@test.com",
        "birthDate": new Date("1981-05-14"),
        "basicSalary": 69948.31896656414,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1969-12-08")
    },
    {
        "id": 28,
        "username": "kate_v",
        "firstName": "Kate",
        "lastName": "Wilson",
        "email": "kate_v@company.com",
        "birthDate": new Date("1996-05-10"),
        "basicSalary": 54796.13456145897,
        "status": "Active",
        "group": "qa",
        "description": new Date("1949-04-07")
    },
    {
        "id": 29,
        "username": "henry_z",
        "firstName": "Henry",
        "lastName": "Moore",
        "email": "henry_z@test.com",
        "birthDate": new Date("1978-06-21"),
        "basicSalary": 60867.54703069502,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1973-11-07")
    },
    {
        "id": 30,
        "username": "grace_thomas",
        "firstName": "Grace",
        "lastName": "Thomas",
        "email": "grace_thomas@test.com",
        "birthDate": new Date("1965-11-26"),
        "basicSalary": 70854.47753466785,
        "status": "Active",
        "group": "sales",
        "description": new Date("1993-04-25")
    },
    {
        "id": 31,
        "username": "kate_wilson",
        "firstName": "Kate",
        "lastName": "Wilson",
        "email": "kate_wilson@test.com",
        "birthDate": new Date("1993-08-04"),
        "basicSalary": 69943.12677426725,
        "status": "Inactive",
        "group": "finance",
        "description": new Date("1984-08-17")
    },
    {
        "id": 32,
        "username": "david.wilson",
        "firstName": "David",
        "lastName": "Wilson",
        "email": "david.wilson@mail.com",
        "birthDate": new Date("1995-01-10"),
        "basicSalary": 73504.83332967387,
        "status": "Active",
        "group": "sales",
        "description": new Date("1931-06-03")
    },
    {
        "id": 33,
        "username": "irene_m",
        "firstName": "Irene",
        "lastName": "Moore",
        "email": "irene_m@company.com",
        "birthDate": new Date("1999-05-13"),
        "basicSalary": 78478.1485551205,
        "status": "Inactive",
        "group": "developer",
        "description": new Date("1994-05-24")
    },
    {
        "id": 34,
        "username": "jack_jackson",
        "firstName": "Jack",
        "lastName": "Jackson",
        "email": "jack_jackson@example.com",
        "birthDate": new Date("1973-04-24"),
        "basicSalary": 62039.163251838756,
        "status": "Active",
        "group": "finance",
        "description": new Date("1961-08-12")
    },
    {
        "id": 35,
        "username": "irene_m",
        "firstName": "Irene",
        "lastName": "Moore",
        "email": "irene_m@company.com",
        "birthDate": new Date("1971-01-02"),
        "basicSalary": 56819.89237425121,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1944-07-19")
    },
    {
        "id": 36,
        "username": "irene_williams",
        "firstName": "Irene",
        "lastName": "Williams",
        "email": "irene_williams@company.com",
        "birthDate": new Date("1964-05-09"),
        "basicSalary": 75958.75253609494,
        "status": "Active",
        "group": "developer",
        "description": new Date("1984-03-16")
    },
    {
        "id": 37,
        "username": "john.j",
        "firstName": "John",
        "lastName": "Jones",
        "email": "john.j@example.com",
        "birthDate": new Date("1999-11-14"),
        "basicSalary": 76022.43370459082,
        "status": "Inactive",
        "group": "support",
        "description": new Date("1957-09-21")
    },
    {
        "id": 38,
        "username": "jack_t",
        "firstName": "Jack",
        "lastName": "Brown",
        "email": "jack_t@company.com",
        "birthDate": new Date("1972-08-14"),
        "basicSalary": 53184.22581262974,
        "status": "Active",
        "group": "marketing",
        "description": new Date("1948-02-09")
    },
    {
        "id": 39,
        "username": "carol.harris",
        "firstName": "Carol",
        "lastName": "Harris",
        "email": "carol.harris@example.com",
        "birthDate": new Date("1984-01-06"),
        "basicSalary": 74082.591532396,
        "status": "Inactive",
        "group": "manager",
        "description": new Date("1905-09-11")
    },
    {
        "id": 40,
        "username": "jack.b",
        "firstName": "Jack",
        "lastName": "Jackson",
        "email": "jack.b@test.com",
        "birthDate": new Date("1965-05-10"),
        "basicSalary": 76479.29743265428,
        "status": "Active",
        "group": "operations",
        "description": new Date("1941-07-01")
    },
    {
        "id": 41,
        "username": "grace5749",
        "firstName": "Grace",
        "lastName": "Johnson",
        "email": "grace5749@example.com",
        "birthDate": new Date("1997-05-13"),
        "basicSalary": 55762.54024085774,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1924-04-03")
    },
    {
        "id": 42,
        "username": "henry_e",
        "firstName": "Henry",
        "lastName": "Thompson",
        "email": "henry_e@company.com",
        "birthDate": new Date("1998-06-07"),
        "basicSalary": 76118.75236849168,
        "status": "Active",
        "group": "manager",
        "description": new Date("1991-01-21")
    },
    {
        "id": 43,
        "username": "irene.smith",
        "firstName": "Irene",
        "lastName": "Smith",
        "email": "irene.smith@company.com",
        "birthDate": new Date("2000-09-03"),
        "basicSalary": 54379.275095731624,
        "status": "Inactive",
        "group": "admin",
        "description": new Date("1926-01-24")
    },
    {
        "id": 44,
        "username": "oliver_smith",
        "firstName": "Oliver",
        "lastName": "Smith",
        "email": "oliver_smith@company.com",
        "birthDate": new Date("1963-01-01"),
        "basicSalary": 50626.25874106196,
        "status": "Active",
        "group": "support",
        "description": new Date("1922-12-06")
    },
    {
        "id": 45,
        "username": "emilyjohnson",
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emilyjohnson@mail.com",
        "birthDate": new Date("1986-08-31"),
        "basicSalary": 51497.43102555341,
        "status": "Inactive",
        "group": "admin",
        "description": new Date("1922-05-27")
    },
    {
        "id": 46,
        "username": "nancy4139",
        "firstName": "Nancy",
        "lastName": "Robinson",
        "email": "nancy4139@company.com",
        "birthDate": new Date("1976-05-05"),
        "basicSalary": 73477.18698082464,
        "status": "Active",
        "group": "support",
        "description": new Date("1958-07-08")
    },
    {
        "id": 47,
        "username": "oliver.w",
        "firstName": "Oliver",
        "lastName": "Davis",
        "email": "oliver.w@test.com",
        "birthDate": new Date("1973-09-18"),
        "basicSalary": 57276.40277230581,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1974-04-20")
    },
    {
        "id": 48,
        "username": "tom_v",
        "firstName": "Tom",
        "lastName": "Jackson",
        "email": "tom_v@test.com",
        "birthDate": new Date("1983-11-06"),
        "basicSalary": 69986.34990928273,
        "status": "Active",
        "group": "marketing",
        "description": new Date("1904-10-19")
    },
    {
        "id": 49,
        "username": "robert_white",
        "firstName": "Robert",
        "lastName": "White",
        "email": "robert_white@mail.com",
        "birthDate": new Date("1976-04-17"),
        "basicSalary": 74479.04315584875,
        "status": "Inactive",
        "group": "support",
        "description": new Date("1992-04-26")
    },
    {
        "id": 50,
        "username": "emily_davis",
        "firstName": "Emily",
        "lastName": "Davis",
        "email": "emily_davis@test.com",
        "birthDate": new Date("1987-09-25"),
        "basicSalary": 58043.14915520608,
        "status": "Active",
        "group": "support",
        "description": new Date("1976-02-02")
    },
    {
        "id": 51,
        "username": "jack.b",
        "firstName": "Jack",
        "lastName": "Jackson",
        "email": "jack.b@test.com",
        "birthDate": new Date("1992-04-14"),
        "basicSalary": 56859.70389938874,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1952-04-12")
    },
    {
        "id": 52,
        "username": "oliver5958",
        "firstName": "Oliver",
        "lastName": "Brown",
        "email": "oliver5958@mail.com",
        "birthDate": new Date("2000-09-26"),
        "basicSalary": 63671.260579318056,
        "status": "Active",
        "group": "sales",
        "description": new Date("1989-04-12")
    },
    {
        "id": 53,
        "username": "emilyjohnson",
        "firstName": "Emily",
        "lastName": "Johnson",
        "email": "emilyjohnson@mail.com",
        "birthDate": new Date("1990-12-24"),
        "basicSalary": 53515.5129605867,
        "status": "Inactive",
        "group": "finance",
        "description": new Date("1952-11-30")
    },
    {
        "id": 54,
        "username": "jack.wilson",
        "firstName": "Jack",
        "lastName": "Wilson",
        "email": "jack.wilson@example.com",
        "birthDate": new Date("1983-06-17"),
        "basicSalary": 58890.53897373358,
        "status": "Active",
        "group": "operations",
        "description": new Date("1972-09-20")
    },
    {
        "id": 55,
        "username": "carolmoore",
        "firstName": "Carol",
        "lastName": "Moore",
        "email": "carolmoore@company.com",
        "birthDate": new Date("1979-10-27"),
        "basicSalary": 68419.00808243889,
        "status": "Inactive",
        "group": "finance",
        "description": new Date("1993-12-10")
    },
    {
        "id": 56,
        "username": "oliver_smith",
        "firstName": "Oliver",
        "lastName": "Smith",
        "email": "oliver_smith@company.com",
        "birthDate": new Date("1969-01-06"),
        "basicSalary": 61868.22674279095,
        "status": "Active",
        "group": "qa",
        "description": new Date("1994-08-06")
    },
    {
        "id": 57,
        "username": "tom.z",
        "firstName": "Tom",
        "lastName": "Taylor",
        "email": "tom.z@company.com",
        "birthDate": new Date("1983-03-31"),
        "basicSalary": 53758.80095063645,
        "status": "Inactive",
        "group": "support",
        "description": new Date("1975-12-12")
    },
    {
        "id": 58,
        "username": "grace5749",
        "firstName": "Grace",
        "lastName": "Johnson",
        "email": "grace5749@example.com",
        "birthDate": new Date("1991-07-09"),
        "basicSalary": 50370.37228536861,
        "status": "Active",
        "group": "developer",
        "description": new Date("1962-07-22")
    },
    {
        "id": 59,
        "username": "tom3677",
        "firstName": "Tom",
        "lastName": "Johnson",
        "email": "tom3677@example.com",
        "birthDate": new Date("1989-04-04"),
        "basicSalary": 58047.93275076315,
        "status": "Inactive",
        "group": "hr",
        "description": new Date("1924-02-07")
    },
    {
        "id": 60,
        "username": "robert6304",
        "firstName": "Robert",
        "lastName": "Jones",
        "email": "robert6304@example.com",
        "birthDate": new Date("1997-12-12"),
        "basicSalary": 74349.59817817707,
        "status": "Active",
        "group": "admin",
        "description": new Date("1998-03-12")
    },
    {
        "id": 61,
        "username": "irene.n",
        "firstName": "Irene",
        "lastName": "Anderson",
        "email": "irene.n@mail.com",
        "birthDate": new Date("1992-08-24"),
        "basicSalary": 65932.13650563723,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1933-05-24")
    },
    {
        "id": 62,
        "username": "frank_w",
        "firstName": "Frank",
        "lastName": "Martin",
        "email": "frank_w@test.com",
        "birthDate": new Date("1986-01-18"),
        "basicSalary": 69237.12748898572,
        "status": "Active",
        "group": "developer",
        "description": new Date("2003-12-05")
    },
    {
        "id": 63,
        "username": "michael_q",
        "firstName": "Michael",
        "lastName": "Robinson",
        "email": "michael_q@example.com",
        "birthDate": new Date("1971-08-05"),
        "basicSalary": 53542.87750826067,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1977-04-25")
    },
    {
        "id": 64,
        "username": "david.wilson",
        "firstName": "David",
        "lastName": "Wilson",
        "email": "david.wilson@mail.com",
        "birthDate": new Date("1979-01-04"),
        "basicSalary": 53541.22943632245,
        "status": "Active",
        "group": "support",
        "description": new Date("1989-09-04")
    },
    {
        "id": 65,
        "username": "tom_white",
        "firstName": "Tom",
        "lastName": "White",
        "email": "tom_white@mail.com",
        "birthDate": new Date("1962-02-11"),
        "basicSalary": 67018.73241749751,
        "status": "Inactive",
        "group": "admin",
        "description": new Date("2003-02-02")
    },
    {
        "id": 66,
        "username": "alice_y",
        "firstName": "Alice",
        "lastName": "Johnson",
        "email": "alice_y@example.com",
        "birthDate": new Date("1969-08-14"),
        "basicSalary": 50629.31457792115,
        "status": "Active",
        "group": "manager",
        "description": new Date("1997-04-24")
    },
    {
        "id": 67,
        "username": "jack_v",
        "firstName": "Jack",
        "lastName": "Robinson",
        "email": "jack_v@test.com",
        "birthDate": new Date("1963-03-03"),
        "basicSalary": 60946.71069001655,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1995-08-23")
    },
    {
        "id": 68,
        "username": "jack_v",
        "firstName": "Jack",
        "lastName": "Robinson",
        "email": "jack_v@test.com",
        "birthDate": new Date("1999-10-03"),
        "basicSalary": 50371.75490616388,
        "status": "Active",
        "group": "developer",
        "description": new Date("1959-05-20")
    },
    {
        "id": 69,
        "username": "samantha.m",
        "firstName": "Samantha",
        "lastName": "Anderson",
        "email": "samantha.m@mail.com",
        "birthDate": new Date("1983-02-18"),
        "basicSalary": 65074.372140343534,
        "status": "Inactive",
        "group": "manager",
        "description": new Date("1956-01-20")
    },
    {
        "id": 70,
        "username": "carolmoore",
        "firstName": "Carol",
        "lastName": "Moore",
        "email": "carolmoore@company.com",
        "birthDate": new Date("1964-02-22"),
        "basicSalary": 75116.10434712369,
        "status": "Active",
        "group": "manager",
        "description": new Date("1989-12-05")
    },
    {
        "id": 71,
        "username": "tom_s",
        "firstName": "Tom",
        "lastName": "Garcia",
        "email": "tom_s@mail.com",
        "birthDate": new Date("1973-01-24"),
        "basicSalary": 63013.3258744324,
        "status": "Inactive",
        "group": "support",
        "description": new Date("1960-01-18")
    },
    {
        "id": 72,
        "username": "oliver_davis",
        "firstName": "Oliver",
        "lastName": "Davis",
        "email": "oliver_davis@test.com",
        "birthDate": new Date("1960-04-18"),
        "basicSalary": 66558.92949232909,
        "status": "Active",
        "group": "hr",
        "description": new Date("1984-07-10")
    },
    {
        "id": 73,
        "username": "john.j",
        "firstName": "John",
        "lastName": "Jones",
        "email": "john.j@example.com",
        "birthDate": new Date("1987-09-22"),
        "basicSalary": 71125.60488806899,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1904-03-22")
    },
    {
        "id": 74,
        "username": "oliver_davis",
        "firstName": "Oliver",
        "lastName": "Davis",
        "email": "oliver_davis@test.com",
        "birthDate": new Date("1964-07-08"),
        "basicSalary": 52204.02013508609,
        "status": "Active",
        "group": "finance",
        "description": new Date("1962-08-03")
    },
    {
        "id": 75,
        "username": "grace_j",
        "firstName": "Grace",
        "lastName": "Brown",
        "email": "grace_j@example.com",
        "birthDate": new Date("2002-10-26"),
        "basicSalary": 76611.03043985389,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1955-05-04")
    },
    {
        "id": 76,
        "username": "irene_m",
        "firstName": "Irene",
        "lastName": "Moore",
        "email": "irene_m@company.com",
        "birthDate": new Date("1963-10-06"),
        "basicSalary": 52281.008907935844,
        "status": "Active",
        "group": "hr",
        "description": new Date("1975-03-06")
    },
    {
        "id": 77,
        "username": "irene.n",
        "firstName": "Irene",
        "lastName": "Anderson",
        "email": "irene.n@mail.com",
        "birthDate": new Date("1994-09-20"),
        "basicSalary": 56991.99823671307,
        "status": "Inactive",
        "group": "developer",
        "description": new Date("1971-12-21")
    },
    {
        "id": 78,
        "username": "henry_z",
        "firstName": "Henry",
        "lastName": "Moore",
        "email": "henry_z@test.com",
        "birthDate": new Date("1968-09-26"),
        "basicSalary": 73302.40194503423,
        "status": "Active",
        "group": "marketing",
        "description": new Date("1902-04-17")
    },
    {
        "id": 79,
        "username": "oliver.w",
        "firstName": "Oliver",
        "lastName": "Davis",
        "email": "oliver.w@test.com",
        "birthDate": new Date("1970-10-10"),
        "basicSalary": 71010.86948182975,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1963-08-19")
    },
    {
        "id": 80,
        "username": "irene_m",
        "firstName": "Irene",
        "lastName": "Moore",
        "email": "irene_m@company.com",
        "birthDate": new Date("1976-12-03"),
        "basicSalary": 74985.54301470476,
        "status": "Active",
        "group": "developer",
        "description": new Date("1969-09-08")
    },
    {
        "id": 81,
        "username": "samantha_r",
        "firstName": "Samantha",
        "lastName": "Brown",
        "email": "samantha_r@example.com",
        "birthDate": new Date("1966-06-27"),
        "basicSalary": 53208.46153313914,
        "status": "Inactive",
        "group": "hr",
        "description": new Date("1985-11-18")
    },
    {
        "id": 82,
        "username": "nancy.t",
        "firstName": "Nancy",
        "lastName": "Thomas",
        "email": "nancy.t@test.com",
        "birthDate": new Date("1979-05-15"),
        "basicSalary": 53768.73707736455,
        "status": "Active",
        "group": "manager",
        "description": new Date("1989-12-24")
    },
    {
        "id": 83,
        "username": "john.j",
        "firstName": "John",
        "lastName": "Jones",
        "email": "john.j@example.com",
        "birthDate": new Date("1979-03-03"),
        "basicSalary": 67659.25059794837,
        "status": "Inactive",
        "group": "manager",
        "description": new Date("1921-04-23")
    },
    {
        "id": 84,
        "username": "patricia_u",
        "firstName": "Patricia",
        "lastName": "Martinez",
        "email": "patricia_u@example.com",
        "birthDate": new Date("1962-12-31"),
        "basicSalary": 63071.11271279444,
        "status": "Active",
        "group": "admin",
        "description": new Date("1916-05-03")
    },
    {
        "id": 85,
        "username": "bob.a",
        "firstName": "Bob",
        "lastName": "Robinson",
        "email": "bob.a@mail.com",
        "birthDate": new Date("1965-12-14"),
        "basicSalary": 70888.07700596485,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1927-07-25")
    },
    {
        "id": 86,
        "username": "emilymoore",
        "firstName": "Emily",
        "lastName": "Moore",
        "email": "emilymoore@company.com",
        "birthDate": new Date("1998-09-10"),
        "basicSalary": 77262.63656510034,
        "status": "Active",
        "group": "hr",
        "description": new Date("1952-08-17")
    },
    {
        "id": 87,
        "username": "oliver_davis",
        "firstName": "Oliver",
        "lastName": "Davis",
        "email": "oliver_davis@test.com",
        "birthDate": new Date("2003-12-23"),
        "basicSalary": 59559.70846607417,
        "status": "Inactive",
        "group": "developer",
        "description": new Date("1917-08-10")
    },
    {
        "id": 88,
        "username": "patricia.white",
        "firstName": "Patricia",
        "lastName": "White",
        "email": "patricia.white@example.com",
        "birthDate": new Date("1964-04-19"),
        "basicSalary": 69591.67720720082,
        "status": "Active",
        "group": "admin",
        "description": new Date("1934-10-15")
    },
    {
        "id": 89,
        "username": "carolrobinson",
        "firstName": "Carol",
        "lastName": "Robinson",
        "email": "carolrobinson@company.com",
        "birthDate": new Date("1985-10-26"),
        "basicSalary": 59302.91423061934,
        "status": "Inactive",
        "group": "sales",
        "description": new Date("1930-08-02")
    },
    {
        "id": 90,
        "username": "grace.anderson",
        "firstName": "Grace",
        "lastName": "Anderson",
        "email": "grace.anderson@mail.com",
        "birthDate": new Date("1975-12-07"),
        "basicSalary": 53551.55614672038,
        "status": "Active",
        "group": "marketing",
        "description": new Date("1956-11-18")
    },
    {
        "id": 91,
        "username": "emily.moore",
        "firstName": "Emily",
        "lastName": "Moore",
        "email": "emily.moore@example.com",
        "birthDate": new Date("1991-08-20"),
        "basicSalary": 61636.36997741675,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1985-12-08")
    },
    {
        "id": 92,
        "username": "tom_v",
        "firstName": "Tom",
        "lastName": "Jackson",
        "email": "tom_v@test.com",
        "birthDate": new Date("1981-04-14"),
        "basicSalary": 50954.826881570065,
        "status": "Active",
        "group": "manager",
        "description": new Date("1916-10-08")
    },
    {
        "id": 93,
        "username": "david.williams",
        "firstName": "David",
        "lastName": "Williams",
        "email": "david.williams@company.com",
        "birthDate": new Date("1985-07-20"),
        "basicSalary": 78746.56434439114,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1946-05-15")
    },
    {
        "id": 94,
        "username": "tom3677",
        "firstName": "Tom",
        "lastName": "Johnson",
        "email": "tom3677@example.com",
        "birthDate": new Date("1971-12-06"),
        "basicSalary": 75648.10041820486,
        "status": "Active",
        "group": "hr",
        "description": new Date("1934-07-08")
    },
    {
        "id": 95,
        "username": "alice.w",
        "firstName": "Alice",
        "lastName": "Jones",
        "email": "alice.w@test.com",
        "birthDate": new Date("1983-11-02"),
        "basicSalary": 67687.78987589995,
        "status": "Inactive",
        "group": "developer",
        "description": new Date("1923-02-23")
    },
    {
        "id": 96,
        "username": "tom3677",
        "firstName": "Tom",
        "lastName": "Johnson",
        "email": "tom3677@example.com",
        "birthDate": new Date("1971-01-24"),
        "basicSalary": 60137.2477313213,
        "status": "Active",
        "group": "sales",
        "description": new Date("1954-12-02")
    },
    {
        "id": 97,
        "username": "henry_e",
        "firstName": "Henry",
        "lastName": "Thompson",
        "email": "henry_e@company.com",
        "birthDate": new Date("1988-04-22"),
        "basicSalary": 70863.19254079935,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1933-03-07")
    },
    {
        "id": 98,
        "username": "alice_y",
        "firstName": "Alice",
        "lastName": "Johnson",
        "email": "alice_y@example.com",
        "birthDate": new Date("1993-10-19"),
        "basicSalary": 50542.09103008778,
        "status": "Active",
        "group": "qa",
        "description": new Date("1921-09-30")
    },
    {
        "id": 99,
        "username": "michael5328",
        "firstName": "Michael",
        "lastName": "Garcia",
        "email": "michael5328@company.com",
        "birthDate": new Date("1975-06-25"),
        "basicSalary": 78154.5409774273,
        "status": "Inactive",
        "group": "hr",
        "description": new Date("1953-12-26")
    },
    {
        "id": 100,
        "username": "oliver.u",
        "firstName": "Oliver",
        "lastName": "Brown",
        "email": "oliver.u@company.com",
        "birthDate": new Date("1994-07-26"),
        "basicSalary": 75471.6870679271,
        "status": "Active",
        "group": "hr",
        "description": new Date("1957-06-26")
    },
    {
        "id": 101,
        "username": "irene.moore",
        "firstName": "Irene",
        "lastName": "Moore",
        "email": "irene.moore@company.com",
        "birthDate": new Date("1993-06-17"),
        "basicSalary": 77105.55479323404,
        "status": "Inactive",
        "group": "sales",
        "description": new Date("1990-10-08")
    },
    {
        "id": 102,
        "username": "jackmartin",
        "firstName": "Jack",
        "lastName": "Martin",
        "email": "jackmartin@company.com",
        "birthDate": new Date("1969-11-16"),
        "basicSalary": 55358.00014420203,
        "status": "Active",
        "group": "sales",
        "description": new Date("1994-06-07")
    },
    {
        "id": 103,
        "username": "grace_smith",
        "firstName": "Grace",
        "lastName": "Smith",
        "email": "grace_smith@example.com",
        "birthDate": new Date("1975-08-22"),
        "basicSalary": 78937.72866828633,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1928-07-02")
    },
    {
        "id": 104,
        "username": "tom_v",
        "firstName": "Tom",
        "lastName": "Jackson",
        "email": "tom_v@test.com",
        "birthDate": new Date("1991-12-24"),
        "basicSalary": 57014.37321504897,
        "status": "Active",
        "group": "marketing",
        "description": new Date("1902-11-21")
    },
    {
        "id": 105,
        "username": "michaelmiller",
        "firstName": "Michael",
        "lastName": "Miller",
        "email": "michaelmiller@example.com",
        "birthDate": new Date("1978-11-11"),
        "basicSalary": 77064.53113341394,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1936-03-16")
    },
    {
        "id": 106,
        "username": "carol_wilson",
        "firstName": "Carol",
        "lastName": "Wilson",
        "email": "carol_wilson@example.com",
        "birthDate": new Date("1977-10-17"),
        "basicSalary": 67480.73582907848,
        "status": "Active",
        "group": "support",
        "description": new Date("1983-06-27")
    },
    {
        "id": 107,
        "username": "irene_w",
        "firstName": "Irene",
        "lastName": "Robinson",
        "email": "irene_w@example.com",
        "birthDate": new Date("1974-01-16"),
        "basicSalary": 56703.827970080965,
        "status": "Inactive",
        "group": "sales",
        "description": new Date("1943-06-08")
    },
    {
        "id": 108,
        "username": "irene.smith",
        "firstName": "Irene",
        "lastName": "Smith",
        "email": "irene.smith@company.com",
        "birthDate": new Date("2001-10-28"),
        "basicSalary": 51091.28060599732,
        "status": "Active",
        "group": "admin",
        "description": new Date("1960-01-27")
    },
    {
        "id": 109,
        "username": "irene.smith",
        "firstName": "Irene",
        "lastName": "Smith",
        "email": "irene.smith@company.com",
        "birthDate": new Date("1967-11-11"),
        "basicSalary": 76379.86734954896,
        "status": "Inactive",
        "group": "hr",
        "description": new Date("1986-09-11")
    },
    {
        "id": 110,
        "username": "bob3085",
        "firstName": "Bob",
        "lastName": "Miller",
        "email": "bob3085@mail.com",
        "birthDate": new Date("2000-05-26"),
        "basicSalary": 66834.07631247211,
        "status": "Active",
        "group": "hr",
        "description": new Date("1908-04-14")
    },
    {
        "id": 111,
        "username": "graceanderson",
        "firstName": "Grace",
        "lastName": "Anderson",
        "email": "graceanderson@company.com",
        "birthDate": new Date("1998-02-25"),
        "basicSalary": 68815.49572982777,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1936-11-23")
    },
    {
        "id": 112,
        "username": "grace_smith",
        "firstName": "Grace",
        "lastName": "Smith",
        "email": "grace_smith@example.com",
        "birthDate": new Date("1961-06-21"),
        "basicSalary": 59117.47705029818,
        "status": "Active",
        "group": "sales",
        "description": new Date("1937-02-28")
    },
    {
        "id": 113,
        "username": "john2699",
        "firstName": "John",
        "lastName": "Jones",
        "email": "john2699@example.com",
        "birthDate": new Date("1976-11-20"),
        "basicSalary": 57226.718312052515,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1943-12-06")
    },
    {
        "id": 114,
        "username": "samanthathomas",
        "firstName": "Samantha",
        "lastName": "Thomas",
        "email": "samanthathomas@mail.com",
        "birthDate": new Date("1984-12-19"),
        "basicSalary": 71524.66009899536,
        "status": "Active",
        "group": "manager",
        "description": new Date("1900-01-12")
    },
    {
        "id": 115,
        "username": "john.j",
        "firstName": "John",
        "lastName": "Jones",
        "email": "john.j@example.com",
        "birthDate": new Date("1998-02-24"),
        "basicSalary": 64091.746805209325,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1977-02-04")
    },
    {
        "id": 116,
        "username": "bob7594",
        "firstName": "Bob",
        "lastName": "Jones",
        "email": "bob7594@mail.com",
        "birthDate": new Date("2000-11-21"),
        "basicSalary": 57509.569225597596,
        "status": "Active",
        "group": "hr",
        "description": new Date("1984-12-31")
    },
    {
        "id": 117,
        "username": "michaelwilson",
        "firstName": "Michael",
        "lastName": "Wilson",
        "email": "michaelwilson@mail.com",
        "birthDate": new Date("1999-09-16"),
        "basicSalary": 76866.76720818468,
        "status": "Inactive",
        "group": "admin",
        "description": new Date("1998-06-04")
    },
    {
        "id": 118,
        "username": "tom_s",
        "firstName": "Tom",
        "lastName": "Garcia",
        "email": "tom_s@mail.com",
        "birthDate": new Date("1960-09-03"),
        "basicSalary": 52452.887642135225,
        "status": "Active",
        "group": "admin",
        "description": new Date("2001-01-25")
    },
    {
        "id": 119,
        "username": "irene_w",
        "firstName": "Irene",
        "lastName": "Robinson",
        "email": "irene_w@example.com",
        "birthDate": new Date("1974-07-20"),
        "basicSalary": 68615.87437510455,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1912-06-01")
    },
    {
        "id": 120,
        "username": "oliver.u",
        "firstName": "Oliver",
        "lastName": "Brown",
        "email": "oliver.u@company.com",
        "birthDate": new Date("1964-06-15"),
        "basicSalary": 73634.53474722014,
        "status": "Active",
        "group": "qa",
        "description": new Date("1912-02-16")
    },
    {
        "id": 121,
        "username": "emilysmith",
        "firstName": "Emily",
        "lastName": "Smith",
        "email": "emilysmith@example.com",
        "birthDate": new Date("1998-02-24"),
        "basicSalary": 71344.16997235888,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1941-05-23")
    },
    {
        "id": 122,
        "username": "patricia0074",
        "firstName": "Patricia",
        "lastName": "Martin",
        "email": "patricia0074@test.com",
        "birthDate": new Date("1963-02-12"),
        "basicSalary": 57565.56879112111,
        "status": "Active",
        "group": "sales",
        "description": new Date("1933-01-26")
    },
    {
        "id": 123,
        "username": "michael_thompson",
        "firstName": "Michael",
        "lastName": "Thompson",
        "email": "michael_thompson@company.com",
        "birthDate": new Date("1966-09-23"),
        "basicSalary": 79115.54532094304,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1903-11-30")
    },
    {
        "id": 124,
        "username": "patricia.e",
        "firstName": "Patricia",
        "lastName": "Miller",
        "email": "patricia.e@mail.com",
        "birthDate": new Date("1992-07-22"),
        "basicSalary": 74527.42403917616,
        "status": "Active",
        "group": "admin",
        "description": new Date("1917-05-17")
    },
    {
        "id": 125,
        "username": "nancy.t",
        "firstName": "Nancy",
        "lastName": "Thomas",
        "email": "nancy.t@test.com",
        "birthDate": new Date("1972-08-10"),
        "basicSalary": 63527.69940145357,
        "status": "Inactive",
        "group": "manager",
        "description": new Date("1993-05-08")
    },
    {
        "id": 126,
        "username": "emily.martin",
        "firstName": "Emily",
        "lastName": "Martin",
        "email": "emily.martin@test.com",
        "birthDate": new Date("1970-02-03"),
        "basicSalary": 59475.69343388043,
        "status": "Active",
        "group": "sales",
        "description": new Date("1952-01-27")
    },
    {
        "id": 127,
        "username": "bobdavis",
        "firstName": "Bob",
        "lastName": "Davis",
        "email": "bobdavis@test.com",
        "birthDate": new Date("1998-06-21"),
        "basicSalary": 78262.22625196015,
        "status": "Inactive",
        "group": "developer",
        "description": new Date("1988-07-25")
    },
    {
        "id": 128,
        "username": "david0264",
        "firstName": "David",
        "lastName": "White",
        "email": "david0264@example.com",
        "birthDate": new Date("1977-02-02"),
        "basicSalary": 73661.40244179264,
        "status": "Active",
        "group": "sales",
        "description": new Date("1997-01-14")
    },
    {
        "id": 129,
        "username": "emily_smith",
        "firstName": "Emily",
        "lastName": "Smith",
        "email": "emily_smith@test.com",
        "birthDate": new Date("1966-09-08"),
        "basicSalary": 78521.30851470758,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1910-11-25")
    },
    {
        "id": 130,
        "username": "victoria8017",
        "firstName": "Victoria",
        "lastName": "Moore",
        "email": "victoria8017@test.com",
        "birthDate": new Date("2003-01-01"),
        "basicSalary": 66343.98651534105,
        "status": "Active",
        "group": "hr",
        "description": new Date("1914-05-23")
    },
    {
        "id": 131,
        "username": "frank_taylor",
        "firstName": "Frank",
        "lastName": "Taylor",
        "email": "frank_taylor@mail.com",
        "birthDate": new Date("1983-01-10"),
        "basicSalary": 58861.692645627736,
        "status": "Inactive",
        "group": "marketing",
        "description": new Date("1920-03-01")
    },
    {
        "id": 132,
        "username": "samantha_williams",
        "firstName": "Samantha",
        "lastName": "Williams",
        "email": "samantha_williams@example.com",
        "birthDate": new Date("1972-12-21"),
        "basicSalary": 73526.2013486943,
        "status": "Active",
        "group": "hr",
        "description": new Date("1973-11-03")
    },
    {
        "id": 133,
        "username": "grace_smith",
        "firstName": "Grace",
        "lastName": "Smith",
        "email": "grace_smith@example.com",
        "birthDate": new Date("1991-02-03"),
        "basicSalary": 65282.3690201943,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1954-04-06")
    },
    {
        "id": 134,
        "username": "oliver5958",
        "firstName": "Oliver",
        "lastName": "Brown",
        "email": "oliver5958@mail.com",
        "birthDate": new Date("1986-01-26"),
        "basicSalary": 68774.01483897034,
        "status": "Active",
        "group": "marketing",
        "description": new Date("1993-07-18")
    },
    {
        "id": 135,
        "username": "michael7758",
        "firstName": "Michael",
        "lastName": "Williams",
        "email": "michael7758@example.com",
        "birthDate": new Date("1973-02-19"),
        "basicSalary": 78610.31357050726,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1912-04-09")
    },
    {
        "id": 136,
        "username": "nancy4139",
        "firstName": "Nancy",
        "lastName": "Robinson",
        "email": "nancy4139@company.com",
        "birthDate": new Date("1980-01-07"),
        "basicSalary": 59709.68259152246,
        "status": "Active",
        "group": "operations",
        "description": new Date("1937-05-18")
    },
    {
        "id": 137,
        "username": "oliver.w",
        "firstName": "Oliver",
        "lastName": "Davis",
        "email": "oliver.w@test.com",
        "birthDate": new Date("1969-03-07"),
        "basicSalary": 77774.62475922043,
        "status": "Inactive",
        "group": "sales",
        "description": new Date("1996-05-12")
    },
    {
        "id": 138,
        "username": "carol.harris",
        "firstName": "Carol",
        "lastName": "Harris",
        "email": "carol.harris@example.com",
        "birthDate": new Date("2002-08-08"),
        "basicSalary": 79946.40150807185,
        "status": "Active",
        "group": "admin",
        "description": new Date("1935-07-14")
    },
    {
        "id": 139,
        "username": "samantha_williams",
        "firstName": "Samantha",
        "lastName": "Williams",
        "email": "samantha_williams@example.com",
        "birthDate": new Date("1997-11-05"),
        "basicSalary": 65683.04080495097,
        "status": "Inactive",
        "group": "manager",
        "description": new Date("1960-12-10")
    },
    {
        "id": 140,
        "username": "john9740",
        "firstName": "John",
        "lastName": "Thomas",
        "email": "john9740@company.com",
        "birthDate": new Date("2001-10-16"),
        "basicSalary": 56041.17760605642,
        "status": "Active",
        "group": "support",
        "description": new Date("1931-03-04")
    },
    {
        "id": 141,
        "username": "david_w",
        "firstName": "David",
        "lastName": "Jones",
        "email": "david_w@company.com",
        "birthDate": new Date("1982-07-12"),
        "basicSalary": 75651.23020584088,
        "status": "Inactive",
        "group": "support",
        "description": new Date("1969-07-10")
    },
    {
        "id": 142,
        "username": "david_w",
        "firstName": "David",
        "lastName": "Jones",
        "email": "david_w@company.com",
        "birthDate": new Date("1964-05-01"),
        "basicSalary": 58471.111367148114,
        "status": "Active",
        "group": "marketing",
        "description": new Date("1901-02-15")
    },
    {
        "id": 143,
        "username": "tom_v",
        "firstName": "Tom",
        "lastName": "Jackson",
        "email": "tom_v@test.com",
        "birthDate": new Date("1979-03-18"),
        "basicSalary": 68918.01414251709,
        "status": "Inactive",
        "group": "manager",
        "description": new Date("1944-05-06")
    },
    {
        "id": 144,
        "username": "irene_m",
        "firstName": "Irene",
        "lastName": "Moore",
        "email": "irene_m@company.com",
        "birthDate": new Date("1989-01-16"),
        "basicSalary": 73034.49055577924,
        "status": "Active",
        "group": "finance",
        "description": new Date("1986-10-08")
    },
    {
        "id": 145,
        "username": "irene_w",
        "firstName": "Irene",
        "lastName": "Robinson",
        "email": "irene_w@example.com",
        "birthDate": new Date("1963-10-18"),
        "basicSalary": 52625.742459321744,
        "status": "Inactive",
        "group": "operations",
        "description": new Date("1935-03-11")
    },
    {
        "id": 146,
        "username": "jack_brown",
        "firstName": "Jack",
        "lastName": "Brown",
        "email": "jack_brown@test.com",
        "birthDate": new Date("1985-05-14"),
        "basicSalary": 52034.7406168186,
        "status": "Active",
        "group": "operations",
        "description": new Date("1999-01-19")
    },
    {
        "id": 147,
        "username": "kate.taylor",
        "firstName": "Kate",
        "lastName": "Taylor",
        "email": "kate.taylor@example.com",
        "birthDate": new Date("1968-07-15"),
        "basicSalary": 68852.24129558637,
        "status": "Inactive",
        "group": "admin",
        "description": new Date("1924-11-17")
    },
    {
        "id": 148,
        "username": "bob.v",
        "firstName": "Bob",
        "lastName": "Thomas",
        "email": "bob.v@example.com",
        "birthDate": new Date("1983-06-07"),
        "basicSalary": 78827.05554660804,
        "status": "Active",
        "group": "sales",
        "description": new Date("1929-07-31")
    },
    {
        "id": 149,
        "username": "oliver.w",
        "firstName": "Oliver",
        "lastName": "Davis",
        "email": "oliver.w@test.com",
        "birthDate": new Date("1992-07-05"),
        "basicSalary": 79694.1376744442,
        "status": "Inactive",
        "group": "qa",
        "description": new Date("1968-07-08")
    },
    {
        "id": 150,
        "username": "tom3677",
        "firstName": "Tom",
        "lastName": "Johnson",
        "email": "tom3677@example.com",
        "birthDate": new Date("1963-05-02"),
        "basicSalary": 61626.79454991072,
        "status": "Active",
        "group": "sales",
        "description": new Date("1909-12-14")
    }
]

// this code use only for create dummy data 
function generateEmployee(countData: number){
  let employee: EmployeeInterface[] = [];
  const group = GROUP_DATA;
  const person = PERSON_DATA;

  for (let i = 1; i <= countData; i++) {
    const randomPerson = person[Math.floor(Math.random() * person.length)];
    const randomGroup = group[Math.floor(Math.random() * group.length)].value;
    
    employee.push({
      id: i,
      username: randomPerson.username,
      firstName: randomPerson.firstName,
      lastName: randomPerson.lastName,
      email: randomPerson.email,
      birthDate: new Date(`${getRandomInt(1960, 2003)}-${getRandomInt(1, 12)}-${getRandomInt(1, 28)}`),
      basicSalary: getRandomInt(50000, 80000) + Math.random(),
      status: i % 2 === 0 ? 'Active' : 'Inactive', 
      group: randomGroup,
      description: new Date(`${getRandomInt(1900, 2003)}-${getRandomInt(1, 12)}-${getRandomInt(1, 28)}`),
    })
  }

  return employee;
}

function getRandomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
// end of this code use only for create dummy data 

